# Generated by Django 4.2.11 on 2025-11-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del cliente')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='RFC')),
                ('tipo_persona', models.IntegerField(choices=[(1, 'Persona Física'), (2, 'Persona Moral')], verbose_name='Tipo de persona')),
                ('estado_id', models.IntegerField(verbose_name='Entidad Federativa (ID)')),
                ('estado_nombre', models.CharField(blank=True, max_length=100, verbose_name='Entidad Federativa')),
                ('codigo_postal', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('municipio_id', models.IntegerField(blank=True, null=True, verbose_name='Municipio (ID)')),
                ('municipio_nombre', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('colonia_id', models.IntegerField(blank=True, null=True, verbose_name='Colonia (ID)')),
                ('colonia_nombre', models.CharField(blank=True, max_length=100, verbose_name='Colonia')),
                ('localidad', models.CharField(blank=True, max_length=8, verbose_name='Localidad')),
                ('sexo', models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, null=True, verbose_name='Sexo')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
